import type { Consejo } from '@/types';

export const consejos: Consejo[] = [
    {
        titulo: 'Preparar el suelo antes de la lluvia',
        slug: 'preparar-suelo-lluvia',
        mes: 5,
        resumen: 'La lluvia de mayo es una oportunidad. Si el suelo no está listo, es un problema.',
        texto: 'Hoyo de 40×40 cm, tierra mezclada con compost, raíces bien extendidas, riego inicial abundante pero sin encharcar. Los primeros 3 meses son clave. Aprovecha la humedad natural para reducir riego artificial.',
        tags: ['suelo', 'lluvia', 'compost'],
        prioridad: 5,
    },
{
    titulo: 'Riego moderado en sequía',
    slug: 'riego-sequia',
    mes: 5,
    resumen: 'En época de calor, riega temprano en la mañana para evitar pérdidas por evaporación.',
    texto: 'Mejor poco y frecuente que mucho y raro. La capa superficial debe mantenerse húmeda para que las raíces jóvenes no se quemen. El riego por goteo es ideal para cítricos jóvenes.',
    tags: ['riego', 'sequía', 'cítricos'],
    prioridad: 4,
},
{
    titulo: 'Control de plagas con Bacillus thuringiensis',
    slug: 'plagas-bt',
    mes: 5,
    resumen: 'Aplica Bacillus thuringiensis en cultivos de hortalizas para combatir orugas.',
    texto: 'El BT es un biocontrolador efectivo contra orugas y larvas. Aplicar al atardecer para evitar degradación por luz solar. En La Vallita no usamos químicos agresivos.',
    tags: ['plagas', 'biológico', 'hortalizas'],
    prioridad: 3,
},
{
    titulo: 'Injerto de mango en verano',
    slug: 'injerto-mango',
    mes: 6,
    resumen: 'El verano es ideal para hacer injertos de mango; asegura buena unión.',
    texto: 'Usar yemas de varetas de 6-8 meses. Injertar en portainjertos sanos. Cubrir con plástico transparente para mantener humedad. Retirar en 15-20 días cuando brote la yema.',
    tags: ['injerto', 'mango', 'técnica'],
    prioridad: 5,
},
{
    titulo: 'Protección contra vientos fuertes',
    slug: 'proteccion-viento',
    mes: 6,
    resumen: 'Junio trae vientos del este. Asegura tus plantas jóvenes con tutorado.',
    texto: 'Las plantas de menos de un año son vulnerables a vientos superiores a 40 km/h. Usar estacas de madera o bambú en triángulo. No apretar demasiado el amarre para permitir crecimiento.',
    tags: ['viento', 'tutorado', 'protección'],
    prioridad: 4,
},
{
    titulo: 'Abonado orgánico para cítricos',
    slug: 'abono-citricos',
    mes: 7,
    resumen: 'Los cítricos agradecen un abono rico en fósforo antes de la floración.',
    texto: 'Aplicar compost maduro alrededor del copón, sin tocar el tronco. Guano de murciélago o ceniza de madera son excelentes fuentes de fósforo natural. Riego posterior para activar nutrientes.',
    tags: ['abono', 'cítricos', 'compost'],
    prioridad: 5,
},
{
    titulo: 'Poda de formación en frutales',
    slug: 'poda-formacion',
    mes: 7,
    resumen: 'Julio es buen momento para podar de formación antes de la floración.',
    texto: 'Eliminar ramas cruzadas, hacia adentro y secas. Mantener copa abierta en forma de vaso para mejor penetración de luz. Desinfectar herramientas entre árbol y árbol.',
    tags: ['poda', 'frutales', 'formación'],
    prioridad: 4,
},
{
    titulo: 'Recolección de semillas nativas',
    slug: 'semillas-nativas',
    mes: 8,
    resumen: 'Agosto es mes de cosecha. Guarda semillas de las mejores plantas.',
    texto: 'Seleccionar frutos del centro de la copa, sanos y maduros. Fermentar semillas de tomate y frutabomba 2-3 días. Secar a la sombra. Etiquetar con fecha y variedad.',
    tags: ['semillas', 'cosecha', 'conservación'],
    prioridad: 5,
},
{
    titulo: 'Control de cochinilla con jabón potásico',
    slug: 'cochinilla-jabon',
    mes: 8,
    resumen: 'La cochinilla ataca en verano. Jabón potásico es tu aliado.',
    texto: 'Preparar solución de 20g de jabón potásico por litro de agua. Aplicar al atardecer, cubriendo todas las partes afectadas. Repetir cada 5 días hasta eliminar.',
    tags: ['plagas', 'cochinilla', 'orgánico'],
    prioridad: 3,
},
{
    titulo: 'Preparación de vivero para invierno',
    slug: 'vivero-invierno',
    mes: 9,
    resumen: 'Septiembre: empieza a preparar protección para el vivero.',
    texto: 'Revisar estructuras de sombra. Limpiar canales de drenaje. Acumular sustrato esterilizado. Revisar stock de bolsas y herramientas. Planificar producción del próximo ciclo.',
    tags: ['vivero', 'planificación', 'infraestructura'],
    prioridad: 4,
},
{
    titulo: 'Siembra de hortalizas de frío',
    slug: 'hortalizas-frio',
    mes: 10,
    resumen: 'Octubre: tiempo de tomate, pimiento y col.',
    texto: 'Sembrar en almácigos protegidos. Transplantar a los 30-35 días. Usar mulch de paja para mantener temperatura del suelo. Proteger de vientos norte con cortinas.',
    tags: ['hortalizas', 'siembra', 'invierno'],
    prioridad: 5,
},
{
    titulo: 'Riego reducido en invierno',
    slug: 'riego-invierno',
    mes: 11,
    resumen: 'Noviembre: las plantas duermen. Reduce el riego a la mitad.',
    texto: 'El crecimiento vegetativo disminuye. Riesgo de pudrición por exceso de agua. Riego solo cuando el sustrato esté seco a 5cm de profundidad. Aprovechar rocío matutino.',
    tags: ['riego', 'invierno', 'cuidado'],
    prioridad: 4,
},
{
    titulo: 'Poda de mantenimiento en frutales maduros',
    slug: 'poda-mantenimiento',
    mes: 12,
    resumen: 'Diciembre: poda sanitaria antes de que empiece el nuevo ciclo.',
    texto: 'Retirar ramas secas, enfermas y chupones. Balancear carga de fruto podando excesos. Aplicar pasta cicatrizante en cortes grandes. Recolectar y quemar restos podados.',
    tags: ['poda', 'mantenimiento', 'sanidad'],
    prioridad: 5,
},
{
    titulo: 'Inicio de germinación temprana',
    slug: 'germinacion-enero',
    mes: 1,
    resumen: 'Enero: germina semillas de frutales para trasplante de primavera.',
    texto: 'Usar sustrato ligero y esterilizado. Mantener a 25-28°C. Humedad constante pero no encharcada. Algunas semillas necesitan escarificación previa (mango, guanábana).',
    tags: ['germinación', 'semillas', 'vivero'],
    prioridad: 5,
},
{
    titulo: 'Control de hormigas con ceniza',
    slug: 'hormigas-ceniza',
    mes: 2,
    resumen: 'Febrero: las hormigas activan. Ceniza seca es barrera efectiva.',
    texto: 'Colocar anillo de ceniza seca alrededor del tronco. Renovar después de lluvias. Para hormigas cortadoras, localizar hormiguero y verter agua hervida con jabón directamente.',
    tags: ['plagas', 'hormigas', 'orgánico'],
    prioridad: 3,
},
{
    titulo: 'Fertilización con compost de estiércol maduro',
    slug: 'fertilizacion-primavera',
    mes: 3,
    resumen: 'Marzo: los frutales despiertan. Dale compost bien maduro.',
    texto: 'Aplicar en corona, 30-50cm del tronco. 2-5kg por planta según tamaño. Cubrir con paja para retener humedad. No usar estiércol fresco: quema raíces y atrae moscas.',
    tags: ['abono', 'compost', 'primavera'],
    prioridad: 5,
},
{
    titulo: 'Transplante de plántulas a campo',
    slug: 'transplante-primavera',
    mes: 4,
    resumen: 'Abril: el suelo está tibio. Es hora de llevar al campo.',
    texto: 'Trasplantar en día nublado o tarde. Hoyo 40×40cm con compost. No enterrar el cuello de la raíz. Riego abundante post-trasplante. Sombra temporal los primeros 7 días.',
    tags: ['trasplante', 'campo', 'primavera'],
    prioridad: 5,
},
];
