import type { Producto } from '@/types';

export const productos: Producto[] = [
    {
        nombre: 'Guayaba',
        slug: 'guayaba',
        cientifico: 'Psidium guajava — Variedades de legado',
        desc: 'Corazón histórico de La Vallita. En su época de esplendor se comercializaron 51,000 plantas de la variedad Lucía y se desarrollaron las Taicuba (1-6) y la Emira, registradas en el libro Especies de frutales. Rápido crecimiento, ideal para mermeladas y consumo fresco.',
        estado: 'legacy',
        precio_cup: 150,
        precio_mlc: 1.50,
        unidad: 'planta',
        categoria: 'frutal',
        tags: ['rápido crecimiento', 'mermelada', 'consumo fresco'],
        variedades: ['Lucía', 'Taicuba 1-6', 'Emira'],
    },
{
    nombre: 'Aguacate',
    slug: 'aguacate',
    cientifico: 'Persea americana',
    desc: 'Variedades adaptadas a suelos de la región. Históricamente parte de las cosechas que superaron los 1,000 quintales entre 2013 y 2017. Excelente sombra y producción sostenida.',
    estado: 'brotando',
    precio_cup: 250,
    precio_mlc: 2.50,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['sombra', 'producción sostenida', 'grasa saludable'],
},
{
    nombre: 'Mango',
    slug: 'mango',
    cientifico: 'Mangifera indica',
    desc: 'Frutal de hoja perenne, sombra amplia y fruto dulce. Clásico de los patios cubanos y pilar histórico de la producción de La Vallita.',
    estado: 'disponible',
    precio_cup: 200,
    precio_mlc: 2.00,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['dulce', 'verano', 'sombra'],
},
{
    nombre: 'Limón criollo',
    slug: 'limon-criollo',
    cientifico: 'Citrus × limon',
    desc: 'Árbol robusto y aromático, esencial en la cocina cubana. Resistente a condiciones locales y de bajo mantenimiento. Ideal para cercas vivas y producción de jugo.',
    estado: 'disponible',
    precio_cup: 120,
    precio_mlc: 1.20,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['ácido', 'medicinal', 'cerca viva'],
},
{
    nombre: 'Limón persa',
    slug: 'limon-persa',
    cientifico: 'Citrus × latifolia',
    desc: 'Variedad de pulpa jugosa y piel fina, muy demandada para cocina y bebidas. Buena adaptación a suelos de Villa Clara con riego moderado.',
    estado: 'disponible',
    precio_cup: 130,
    precio_mlc: 1.30,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['cocina', 'bebidas', 'jugoso'],
},
{
    nombre: 'Mandarina',
    slug: 'mandarina',
    cientifico: 'Citrus reticulata',
    desc: 'Fruto dulce y aromático, de fácil peladura. Árbol de porte mediano, ideal para patios y pequeñas parcelas. Muy apreciada en la región central de Cuba.',
    estado: 'brotando',
    precio_cup: 180,
    precio_mlc: 1.80,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['dulce', 'patios', 'fácil'],
},
{
    nombre: 'Naranja',
    slug: 'naranja',
    cientifico: 'Citrus × sinensis / Citrus × aurantium',
    desc: 'Incluye variedades dulces y agrias (naranja agria). Robusta, resistente a sequía y ideal para cercas vivas, jugo y cocina. Clásico de los patios cubanos.',
    estado: 'disponible',
    precio_cup: 140,
    precio_mlc: 1.40,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['jugo', 'cocina', 'resistente'],
},
{
    nombre: 'Uva',
    slug: 'uva',
    cientifico: 'Vitis vinifera',
    desc: 'Frutal exótico cultivado históricamente en La Vallita como parte de su apuesta por la diversidad. Requiere tutorado y riego controlado, pero recompensa con frutos de alto valor.',
    estado: 'encargo',
    precio_cup: 350,
    precio_mlc: 3.50,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['exótico', 'tutorado', 'alto valor'],
},
{
    nombre: 'Melocotón',
    slug: 'melocoton',
    cientifico: 'Prunus persica',
    desc: 'Frutal de clima templado adaptado con éxito en La Vallita. Fruto jugoso y dulce, parte del legado de frutas no tropicales que Emilio logró establecer en Villa Clara.',
    estado: 'encargo',
    precio_cup: 300,
    precio_mlc: 3.00,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['templado', 'jugoso', 'no tropical'],
},
{
    nombre: 'Frutabomba',
    slug: 'frutabomba',
    cientifico: 'Carica papaya',
    desc: 'Rápido crecimiento y producción en menos de un año. Históricamente uno de los cultivos de mayor volumen en La Vallita, con cosechas que aportaron a los 1,000+ quintales de la finca.',
    estado: 'disponible',
    precio_cup: 80,
    precio_mlc: 0.80,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['rápido', 'alto volumen', 'cocina'],
},
{
    nombre: 'Guanábana',
    slug: 'guanabana',
    cientifico: 'Annona muricata',
    desc: 'Frutal nativo de hoja perenne, apreciado por su pulpa blanca y sabor ácido-dulce. Usada en jugos, dulces y postres. De porte mediano, se adapta bien a la sombra parcial.',
    estado: 'brotando',
    precio_cup: 220,
    precio_mlc: 2.20,
    unidad: 'planta',
    categoria: 'frutal',
    tags: ['nativo', 'jugos', 'sombra parcial'],
},
{
    nombre: 'Plátano',
    slug: 'platano',
    cientifico: 'Musa × paradisiaca',
    desc: 'Plátano macho y de cocinar, resistente. Rápido crecimiento y alta producción de biomasa. Ideal para sombra intercalada.',
    estado: 'disponible',
    precio_cup: 60,
    precio_mlc: 0.60,
    unidad: 'planta',
    categoria: 'hortaliza',
    tags: ['cocina', 'sombra', 'rápido'],
},
{
    nombre: 'Moringa',
    slug: 'moringa',
    cientifico: 'Moringa oleifera',
    desc: 'Superalimento de hojas nutritivas. Resistente a sequía y de rápido crecimiento. Usada en infusiones, cocina y como suplemento natural.',
    estado: 'disponible',
    precio_cup: 50,
    precio_mlc: 0.50,
    unidad: 'planta',
    categoria: 'hortaliza',
    tags: ['nutritiva', 'medicinal', 'sequía'],
},
];
